server:
  port: 10001
# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.40.236.91:3306/grain_mall_pms?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: grain_mall_pms
    password: yzYbW8cEyrkMiZA2
  cloud:
    nacos:
      discovery:
        server-addr: 110.40.236.91:8848
  application:
    name: mall-product
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto