spring:
  cloud:
    nacos:
      discovery:
        server-addr: 110.40.236.91:8848
    gateway:
      routes:
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /renren-fast/$\{segment}
  application:
    name: gateway-server
server:
  port: 10006